### ISSUE TITLE
asking for help,thx

### ISSUE THREAD

**Issue by qchaha** [mohabusama/pyguacamole#4]
hello，when i according to tutor，
client.handshake(protocol='rdp', hostname='localhost', port=3389)
it returns an error:
AttributeError: 'NoneType' object has no attribute 'endswith'

all logs output:
------------------------------------------------------------------------------------------------------------------
>>> from guacamole.client import GuacamoleClient
>>> client = GuacamoleClient('127.0.0.1', 4822)
>>> client.handshake(protocol='rdp', hostname='localhost', port=3389)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/py/integrate-server/flask/lib/python3.6/site-packages/guacamole/client.py", line 159, in handshake
    instruction = self.read_instruction()
  File "/root/py/integrate-server/flask/lib/python3.6/site-packages/guacamole/client.py", line 127, in read_instruction
    return Instruction.load(self.receive())
  File "/root/py/integrate-server/flask/lib/python3.6/site-packages/guacamole/instruction.py", line 69, in load
    if not instruction.endswith(INST_TERM):
AttributeError: 'NoneType' object has no attribute 'endswith'
>>> 
-------------------------------------------------------------------------------------------------------------------

thx for your help.

**Comment by qchaha** [comment]
oh,i am figure out that,i met that error due to guacamole's version,and i am updating to lastest,it's ok! thx !

**Comment by VukAnd** [comment]
are you going to close this now?

**Comment by mohabusama** [comment]
Closing as it seems to be resolved.
